name: .NET CI Pipeline - FoodServiceInventoryApp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'
  
  SOLUTION_ROOT_DIR: 'FoodServiceInventoryApp' 
  
  SOLUTION_FILE_NAME: 'FoodServiceInventoryApp.sln' 
  
  TEST_PROJECT_PATH: 'FoodServiceInventoryApp.Tests/FoodServiceInventoryApp.Tests.csproj'
  
  RUNSETTINGS_FILE_PATH: 'FoodServiceInventoryApp.Tests/test.runsettings' 

  TEST_RESULTS_DIR: './TestResults' 
  
  COVERAGE_COBERTURA_FILE_NAME: 'coverage.cobertura.xml'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      working-directory: ${{ env.SOLUTION_ROOT_DIR }}
      run: dotnet restore ${{ env.SOLUTION_FILE_NAME }}

    - name: Build solution
      working-directory: ${{ env.SOLUTION_ROOT_DIR }}
      run: dotnet build ${{ env.SOLUTION_FILE_NAME }} --no-restore --configuration Release

    - name: Install Coverlet and ReportGenerator Tools
      run: |
        dotnet tool install --global coverlet.console --version 6.0.0
        dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.0

    - name: Run Unit Tests with Coverage
      working-directory: ${{ env.SOLUTION_ROOT_DIR }}
      run: |
        dotnet test ${{ env.TEST_PROJECT_PATH }} \
          --no-build \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --settings "${{ env.RUNSETTINGS_FILE_PATH }}" \
          --results-directory "${{ env.TEST_RESULTS_DIR }}" \
          --logger "trx;LogFileName=test_results.trx" \
          --verbosity normal

    - name: Generate Coverage Report
      working-directory: ${{ env.SOLUTION_ROOT_DIR }}
      run: |
        reportgenerator "-reports:${{ env.TEST_RESULTS_DIR }}/**/${{ env.COVERAGE_COBERTURA_FILE_NAME }}" `
          "-targetdir:./CoverageReport" `
          "-reporttypes:Html" `
          "-assemblyfilters:+FoodServiceInventoryApp;+FoodServiceInventoryApp.ViewModels" `
          "-filefilters:-*Tests;+*;-*Migrations*;**/*.xaml;**/*.xaml.cs;**obj\**\Views\**\*.g.cs;**Views\**\*.cs"
      
    - name: Upload Test Results Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ${{ env.SOLUTION_ROOT_DIR }}/${{ env.TEST_RESULTS_DIR }}
        retention-days: 5

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CodeCoverageReport
        path: ${{ env.SOLUTION_ROOT_DIR }}/CoverageReport
        retention-days: 5
