name: .NET CI Pipeline
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
env:
  DOTNET_VERSION: '8.0.x'

  SOLUTION_DIR: 'FoodServiceInventoryApp' 
  
  PROJECT_TESTS: 'FoodServiceInventoryApp.Tests/FoodServiceInventoryApp.Tests.csproj'

  COVERAGE_REPORT_PATH: 'FoodServiceInventoryApp.Tests/TestResults/Coverage/cobertura.xml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.SOLUTION_DIR }}

    - name: Build project
      run: dotnet build --no-restore --configuration Release
      working-directory: ${{ env.SOLUTION_DIR }}

    - name: Run tests with coverage
      run: |
        # Запускаем тесты с coverlet для сбора покрытия.
        # Пути PROJECT_TESTS и COVERAGE_REPORT_PATH уже относительны SOLUTION_DIR,
        # так как 'working-directory' установлен.
        dotnet test ${{ env.PROJECT_TESTS }} \
          --no-build \
          --configuration Release \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=cobertura \
          /p:CoverletOutput=${{ env.COVERAGE_REPORT_PATH }} \
          --results-directory ./TestResults \
          --logger "trx;LogFileName=test_results.trx"
      working-directory: ${{ env.SOLUTION_DIR }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          ${{ env.SOLUTION_DIR }}/TestResults/test_results.trx # Путь к файлу результатов тестов (.trx)
          ${{ env.SOLUTION_DIR }}/${{ env.COVERAGE_REPORT_PATH }} # Путь к отчету о покрытии (cobertura.xml)

    - name: Publish code coverage report
      uses: danielpalme/ReportGenerator-Action@v5
      with:
        reports: ${{ env.SOLUTION_DIR }}/${{ env.COVERAGE_REPORT_PATH }} 
        targetdir: 'coverage_html'
        reporttypes: 'Html'

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: coverage_html
